name: optics-operators
version: 0.1.0.0

library:
  source-dirs:
    - src

executables:
  readme:
    main: README.lhs
    source-dirs:
      - .
      - src
    ghc-options: -pgmL markdown-unlit

tests:
  unit-test:
    main: Main.hs
    source-dirs:
      - src
      - test
    dependencies:
      - tasty >= 1.4.3 && < 1.5
      - tasty-quickcheck >= 0.10.2 && < 0.11

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  - -Wall
  - -Wno-name-shadowing

dependencies:
  - base >= 4.10 && < 5
  - optics-core >= 0.4 && < 1
  - mtl >= 2 && < 3
