name: optics-operators
version: 0.1.0.2
license: MIT
license-file: LICENSE
author: qwbarch
maintainer: qwbarch <qwbarch@gmail.com>
category: Data, Optics, Lenses
homepage: https://github.com/qwbarch/optics-operators
bug-reports: https://github.com/qwbarch/optics-operators/issues
extra-doc-files: CHANGELOG.md

synopsis: A tiny package containing operators missing from the official package.
description: |
  A tiny package containing operators missing from the official package.
  Basic example using state operators:

  > newtype Person = Person { age :: Int } deriving (Show, Generic)
  > 
  > main :: IO ()
  > main = print <=< flip execStateT (Person 0) $ do
  >   #age += 50
  >   #age -= 20
  >
  > -- Output: Person {age = 30}

flags:
  build-readme:
    description: "Build the literate haskell README example."
    default: false
    manual: false

library:
  source-dirs:
    - src

executables:
  readme:
    when:
      condition: "!flag(build-readme)"
      buildable: False
    main: README.lhs
    source-dirs:
      - .
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -flate-specialise
      - -fspecialise-aggressively
      - -Wall
      - -Wno-name-shadowing
      - -pgmL markdown-unlit

tests:
  unit-test:
    main: Main.hs
    source-dirs:
      - src
      - test
    dependencies:
      - tasty >= 1.4.3 && < 1.5
      - tasty-quickcheck >= 0.10.2 && < 0.11
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -flate-specialise
      - -fspecialise-aggressively
      - -Wall
      - -Wno-name-shadowing

dependencies:
  - base >= 4.10 && < 5
  - optics-core >= 0.4 && < 1
  - mtl >= 2 && < 3
